spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batchDB
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false
  application:
    name: batchProcessingDemo
server:
  port: 9090






#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/BatchDB
#    password: new_password
#    username: root
#  jpa:
#    database-platform: org.springframework.orm.jpa.vendor.Database.MYSQL
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        globally_quoted_identifiers: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#  application:
#    name: springSecurityRoleBasedAccess


#    url: jdbc:mysql://192.168.1.216:3306/employee
