

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batchDb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false
  application:
    name: batchProcessingDemo
server:
  port: 9090
