spring:
  datasource:
    url: jdbc:postgresql://postgres_con:5432/batchDB  # Use service name instead of localhost
    username: postgres  # Match the username defined in docker-compose
    password: password  # Match the password defined in docker-compose
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true  # Set to true for debugging SQL queries
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false
  application:
    name: batchProcessingDemo
server:
  port: 9090
